### POST
POST http://localhost:5000/api/v1/admin/add
Content-Type: application/json

{
  "first_name":"Azizbek",
  "last_name": "Akramov",
  "phone_number": "+998335689962",
  "username": "aziz.akramov",
  "role": "admin",
  "password":"1234"
}



### GET
GET http://localhost:5000/api/v1/contract/list
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJyb2xlIjoic3VwZXJfYWRtaW4iLCJjcmVhdGVkX3RpbWUiOiIyMDI0LTExLTAyVDA5OjM5OjI1LjE4OFoifSwiaWF0IjoxNzMwNTQwMzY1LCJleHAiOjE3MzExNDUxNjV9.8bRMrGX8zaCrUo0c8RNJokxwsbCw09dpzmnRo8S6oDY


### POST LOGIN
POST http://localhost:5000/api/v1/admin/login
Content-Type: application/json

{
  "username": "sherozbek",
  "password": "1234"
}